apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: openshift-gitops-placement
  namespace: open-cluster-management
placementRef:
  name: openshift-gitops-placement
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: openshift-gitops
    apiGroup: policy.open-cluster-management.io
    kind: Policy