apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "25"
  name: team-argocd
  namespace: cluster-ops
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
