apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-config
  namespace: cluster-ops
spec:
  generators:
  - matrix:
      generators:
      - merge:
          generators:
          - clusterDecisionResource:
              configMapRef: acm-placement
              labelSelector:
                matchLabels:
                  cluster.open-cluster-management.io/placement: gitops
          - clusters: {}
          mergeKeys:
          - server
      - list:
          elements:
            - template: bootstrap
  template:
    metadata:
      name: "config-{{metadata.labels.deploymentType}}-{{clusterName}}-{{template}}"
      labels:
        deploymentType: "{{metadata.labels.deploymentType}}" 
        #region: "{{metadata.labels.region}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/misanche/gitops-for-organizations.git
        targetRevision: main
        path: base/components/{{template}}
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            - /conf/{{metadata.labels.deploymentType}}/conf.yaml
            - /clusters/{{metadata.labels.deploymentType}}/{{clusterName}}/conf.yaml
          values: |
            api: "{{server}}"
      destination:
        #server: "{{cluster.address}}"
        server: "https://kubernetes.default.svc"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - Validate=true